# Generated by Django 3.2.5 on 2021-09-25 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(max_length=200)),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=200)),
                ('discount', models.IntegerField()),
                ('image', models.TextField()),
                ('category', models.CharField(choices=[('L', 'laptop'), ('PC', 'computer'), ('CPU', 'cpu'), ('SHI', 'shirt'), ('CTH', 'clothes'), ('MOB', 'mobile'), ('CAM', 'camera'), ('APP', 'appliances'), ('TAB', 'tablet'), ('HOM', 'home_decorators'), ('MED', 'medicines'), ('STA', 'stationery'), ('GRO', 'grocery'), ('CUT', 'cutlery'), ('GC', 'gaming_consoles'), ('PCA', 'computer_accessories'), ('SPE', 'spectacles'), ('BUK', 'books'), ('WAT', 'watch'), ('TUL', 'tools'), ('DIS', 'dishes'), ('ACS', 'accessories'), ('ESS', 'essentials')], max_length=3)),
                ('price', models.IntegerField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('total', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
