# Generated by Django 3.2.5 on 2021-10-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='intent_id',
            field=models.CharField(default='po', max_length=250),
            preserve_default=False,
        ),
    ]
