# Generated by Django 3.2.5 on 2021-10-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default='product', max_length=25),
            preserve_default=False,
        ),
    ]
