# Generated by Django 3.2.5 on 2021-10-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('INR', 'in review'), ('NOT', 'noted'), ('SOL', 'solved')], default='in review', max_length=50),
            preserve_default=False,
        ),
    ]
